# Generated by Django 3.0.5 on 2020-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(default='to be updated')),
                ('use_case', models.TextField(default='to be updated')),
                ('lang', models.CharField(default='VB.NET', max_length=50)),
                ('version', models.IntegerField(default=2019)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.CharField(max_length=70)),
                ('source_code', models.URLField(blank=True)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('meta_description', models.TextField(default='')),
                ('meta_keyword', models.TextField(default='')),
            ],
        ),
    ]
